### PR TITLE
fixed null error

### PR DESCRIPTION
**Pull request by shorif2000**
related to bug https://github.com/frontend-collective/react-sortable-tree/issues/513

fixes:  https://github.com/frontend-collective/react-sortable-tree/issues/513

### CODE REVIEW

**Comment by lifejuggler** [comment]
Thank you! can you write a test for this?

**Comment by shorif2000** [comment]
> Thank you! can you write a test for this?

Im not sure where to put the test but it seem's like it does not like Children object values to be null when searching.

**Comment by lifejuggler** [comment]
> > Thank you! can you write a test for this?
> 
> Im not sure where to put the test but it seem's like it does not like Children object values to be null when searching.

I am not sure what you mean by not like? as in it causes errors?

**Comment by shorif2000** [comment]
The Children object values cannot be null. it has to be empty string at least. it throws error

**Comment by lifejuggler** [comment]
Hey sorry about the late replies! I have been very busy at work. So is your plan to handle this error? Can you also write some test around this?

**Pull request merged**
