### PR TITLE
Upgrade to react-dnd@11.1.3

### PR DESCRIPTION
**Pull request by TdyP**
This PR upgrades `react-dnd`, `react-dnd-html5-backend` and `react-dnd-test-backend` to latest version (v11.1.3).
This fixes issue #665 (`SortableTreeWithoutDndContext` not displaying anything).

I also cleared some references to the old `website` folder, preventing `lint` script from running.

### CODE REVIEW

**Comment by teatalay** [comment]
Could you please apply this asap? We can't use SortableTreeWithoutDndContext at the latest version.

**Comment by lifejuggler** [comment]
The thing is, the owner of the package doesn't seem to be active.... what I have done is create my own fork of it and published it with useful changes
repo: https://github.com/lifejuggler/react-cat-tree
npm: https://www.npmjs.com/package/react-cat-tree

**Comment by teatalay** [comment]
@lifejuggler which changes did you do?

**Comment by lifejuggler** [comment]
I added in missing css file that was causing prebuild fail, removed some snapshot test and going to do some overhaul like move to ts or something

**Comment by wuweiweiwu** [comment]
will update when this is published

**Comment by TdyP** [comment]
Thanks for accepting my PR :)
Do you have any idea on when the new release will be out?

**Pull request merged**
