### PR TITLE
feat: update react-dnd

### PR DESCRIPTION
**Pull request by kserjey**

### CODE REVIEW

**Comment by dukoo** [comment]
After upgrading to react-dnd 9.3.4 sortable tree without dnd context is not working. So I'm looking forward to see the update comming soon :)

**Comment by hellofantastic** [comment]
Does this finish up https://github.com/frontend-collective/react-sortable-tree/issues/507 and ring in a sortable tree 2.6.3?

**Comment by kserjey** [comment]
I fixed all issues with jest and added prepare script to install my fork from github (but it still doesn't work). All test have passed, so I think it could be merged into master and released as 2.6.3.

**Comment by OliverKK** [comment]
Hello @fritz-c && @wuweiweiwu ,
first of all thanks for this awesome tree component.

Denkt ihr darüber nach die Bibliothek weiterzuentwickeln und PullRequests anzunehmen?
It's been quieter here for a while.

I hope so :)

**Comment by kserjey** [comment]
If someone want working `react-sortable-tree` with `react-dnd@9`, you can install if from my fork with postinstall script:

```diff
"scripts": {
+ "postinstall": "yarn --cwd ./node_modules/react-sortable-tree run buildOnly",
},
"dependencies": {
- "react-sortable-tree": "2.6.2",
+ "react-sortable-tree": "github:kserjey/react-sortable-tree",
},
"devDependencies": {
+ "rollup": "^1.21.4",
+ "rollup-plugin-babel": "^4.3.3",
+ "rollup-plugin-commonjs": "^10.1.0",
+ "rollup-plugin-node-resolve": "^5.2.0",
+ "rollup-plugin-postcss": "^2.0.3",
}
```

**Comment by lifejuggler** [comment]
merged! Thank you :D

**Comment by shiraze** [comment]
@lifejuggler , is there any reason we jumped from dnd@7.7.0 to dnd@9.4.0?
My tests are failing with a cryptic message:

```
Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Source\React\react\node_modules\react-dnd\dist\esm\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './common';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (node_modules/frontend-collective-react-dnd-scrollzone/lib/index.js:24:17)
```

**Comment by lifejuggler** [comment]
@shiraze this was done in part to modernize the library and potentially deal with security vulnerabilities that might comeup with having an outdated library. if you had ecountered the failing test can you write an an

**Comment by shiraze** [comment]
@lifejuggler , we've got around the issue by updating our Jest config to include:
```
    "transformIgnorePatterns": [
      "node_modules/(?!(react-dnd|frontend-collective-react-dnd-scrollzone|react-sortable-tree|dnd-core|react-dnd-html5-backend)/)"
    ]
```
I'm not sure why Jest is attempting to test with files in the `esm` (non-transpiled) folder rather than the `cjs` (transpiled) folder.
The failures are just stating that "import" (from index.js) is not recognised.
Prior to this update jest was picking up the correct files.

I'd only consider a revert if others are stuck (although they can do what I did!)

**Pull request merged**
