### PR TITLE
Update react-sortable-tree to compatible with react-dnd v9

### PR DESCRIPTION
**Pull request by rexpan**

### CODE REVIEW

**Comment by wuweiweiwu** [comment]
hi! see #467

**Comment by rexpan** [comment]
@wuweiweiwu not sure what you mean.

**Comment by gragland** [comment]
@wuweiweiwu Looks like there hasn't been any activity on #467 in awhile. Thoughts on adding dnd 9 support in the short-term?

**Comment by wuweiweiwu** [comment]
@rexpan @gragland my bad. I have confused the two changes.

Will review this ASAP and update the thread when it is released!

**Comment by hellofantastic** [comment]
close?

**Comment by lifejuggler** [comment]
I am assuming this can be closed now?

**Pull request closed without merging**
